#include "autogenerated.h"

void READMEMORYBYADDRESS(void ) __attribute__((section(".code"))) ;
void READMEMORYBYADDRESS ()
{
    uint8_t* kwp_bytes;
    // Move R4 to pointer1 var, so we can start working with it
    asm ("mr  %0, 4" : "=r" (kwp_bytes));
    uint32_t memory_address = (uint32_t)kwp_bytes[0] << 16 | (uint32_t)kwp_bytes[1] << 8 | (uint32_t)kwp_bytes[2];
    uint8_t memory_len = (uint8_t)kwp_bytes[3];
    kwp_bytes[0] = 0x63;
    int i;
    for(i = 0; i < memory_len; i++ ){
        kwp_bytes[1 + i] = READ_RAM_BYTE(memory_address+i);
    }
}