#include "autogenerated.h"

void READMEMORYBYADDRESS(void* r3, void* r4 ) __attribute__((section(".code"))) ;
void READMEMORYBYADDRESS (void* r3, void* r4)
{
    int* r12 = (int*)r4;
    *r12 = 0x63;   // lwz r12, 0x0(r4)
    short r10 = 0x1;
    *(short*)(r4 + 0x8) = r10;  // sth r10, 0x8(r4)
    unsigned char r9 = 0x2;
    *(unsigned char*)(r4 + 0xa) = r9;  // stb r9, 0xa(r4)
}
