#include "autogenerated.h"


struct kwp_input_struct {
    uint32_t element0;
    uint8_t element4;
    uint8_t element5;
    uint8_t element6;
    uint8_t element7;
    uint16_t msg_len;  // Offset 0x8
    uint8_t  ret_status;  // Offset 0xA
};


int READMEMORYBYADDRESS() __attribute__((section(".code"))) ;
int READMEMORYBYADDRESS ()
{
    unsigned char* kwp_answer;
    struct kwp_input_struct* r4;
    //register int *r5 asm ("r4");
    asm ("mr  %0, 4" : "=r" (r4));


    // 1 means ok, 2 is bad request. Will be added to KWP output code.
    r4->ret_status = 0x1;
    // Msg Len
    r4->msg_len = 0x2;
    // Answer Buffer:
    kwp_answer = ((unsigned char *)r4->element0);
    kwp_answer[0] = 0x12;

    return r4->ret_status;
}
