#include "autogenerated.h"
#define WRITE_RAM_BYTE(address,value) (*((uint8_t *)(address))) = value;

void WRITEMEMORYBYADDRESS(void ) __attribute__((section(".code"))) ;
void WRITEMEMORYBYADDRESS ()
{
    uint8_t* kwp_bytes;
    // Move R4 to pointer1 var, so we can start working with it
    asm ("mr  %0, 4" : "=r" (kwp_bytes));
    uint32_t memory_address = (uint32_t)kwp_bytes[0] << 16 | (uint32_t)kwp_bytes[1] << 8 | (uint32_t)kwp_bytes[2];
    uint8_t memory_len = (uint8_t)kwp_bytes[3];
    kwp_bytes[0] = 0x7D;
    int i;
    for(i = 0; i < memory_len; i++ ){
        WRITE_RAM_BYTE(memory_address+i,kwp_bytes[1 + i]);
    }
}